**1**

In [1]:
import numpy as np

In [2]:
# buat vector i dengan elemen (1,0) dan vector j dengan elemen (0,1)

i = np.array([1, 0])
i

array([1, 0])

In [3]:
j= np.array([0,1])
j

array([0, 1])

In [4]:
# buktikan bahwa vector i dan vector j itu orthogonal

np.dot(i, j)

np.int64(0)

**2**

In [5]:
# Bagaimana dengan v=(1,2) dan w=(2,-1), apakah juga orthogonal?

v = np.array([1, 2])
v

array([1, 2])

In [6]:
w = np.array([2, -1])
w

array([ 2, -1])

In [7]:
np.dot(v, w)

np.int64(0)