**1**

In [1]:
# buat matrix X berukuran 2x3 menggunakan numpy
import numpy as py

X = py.array([[1,2,0],
              [2,1,0]])
print(X)

[[1 2 0]
 [2 1 0]]


In [3]:
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [2]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([1, 2])

In [4]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([2, 1, 0])

**2**

*  pytorch

In [5]:
# buat matrix X berukuran 2x3 menggunakan pytorch
import torch

X = torch.tensor([[1,2,0],
                  [2,1,0]])
X

tensor([[1, 2, 0],
        [2, 1, 0]])

In [6]:
# tampilkan ukuran dari matrix X menggunakan pytorch
X.shape

torch.Size([2, 3])

In [7]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X menggunakan pytorch
X[:,0]

tensor([1, 2])

In [ ]:
# tampilkan seluruh elemen dari baris kedua dari matrix X menggunakan pytorch
X[1,:]

tensor([2, 1, 0])


*   TensorFlow



In [ ]:
import tensorflow as tf

In [ ]:
# buat matrix X berukuran 2x3 menggunakan tensorflow

X = tf.Variable([[1,2,0],
                [2,1,0]])
X

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 0],
       [2, 1, 0]], dtype=int32)>

In [ ]:
# tampilkan ukuran dari matrix X menggunakan tensorflow
tf.shape(X)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [ ]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X menggunakan tensorflow
X[:,0]

array([1, 2])

In [ ]:
# tampilkan seluruh elemen dari baris kedua dari matrix X menggunakan tensorflow
X[1,:]

array([2, 1, 0])