In [1]:
# 1. buat vector x dengan ukuran 3x1

import numpy as np

x = np.array([[1],
              [2],
              [0]])
x

array([[1],
       [2],
       [0]])

In [2]:
# - hitung panjang vector x

len(x)

3

In [3]:
# - tampilkan ukuran vector x

x.shape

(3, 1)

In [15]:
# - tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [17]:
# akses elemen pertama dari vector x
x[0]

array([1])

In [18]:
# -  tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

**2**

In [ ]:
# 2. lakukan transpose pada vector x dan simpan pada variabel x_t

x_t = x.T
x_t

array([[1, 2, 0]])

In [ ]:
# tampilkan ukuran dari vector x_t

x_t.shape

(1, 3)

In [ ]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[2, 1, 0]])

y_t = y.T
y_t

array([[2],
       [1],
       [0]])

In [ ]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

3. **lakukan soal nomor 2 menggunakan pytorch dan tensorflow**


*   pytorch




In [ ]:
# lakukan transpose pada vector x dan simpan pada variabel x_t menggunakan pytorch
import torch

x = torch.tensor([[1],
              [2],
              [0]])

x_t = x.t() #sintaks yang diperlukan tidak tersedia di file bapak
x_t

tensor([[1, 2, 0]])

In [ ]:
# tampilkan ukuran dari vector x_t menggunnakan pytorch
x_t.shape

torch.Size([1, 3])

In [ ]:
# lakukan transpose pada vector y dan simpan pada variabel y_t menggunakan pytorch
y = torch.tensor([2, 1, 0])

y_2d = y.unsqueeze(0) #sintaks yang diperlukan tidak tersedia di file bapak
y_t = y_2d.t()
y_t

tensor([[2],
        [1],
        [0]])

In [ ]:
# tampilkan ukuran dari vector x_t menggunakan pytorch
x_t.shape




*   Tensorflow



In [ ]:
import tensorflow as tf

In [ ]:
# lakukan transpose pada vector x dan simpan pada variabel x_t menggunakan tensorflow
x = tf.Variable([[1],
              [2],
              [0]])

x_t = tf.transpose(x)   #sintaks yang diperlukan tidak tersedia di file bapak#sintaks yang diperlukan tidak tersedia di file bapak
x_t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 0]], dtype=int32)>

In [ ]:
# tampilkan ukuran dari vector x_t menggunakan tensorflow
x_t.shape

(1, 3)

In [ ]:
# lakukan transpose pada vector y dan simpan pada variabel y_t menggunakan tensorflow
y = tf.Variable([2, 1, 0])

y_2d = tf.expand_dims(y, axis=0)  #sintaks yang diperlukan tidak tersedia di file bapak#sintaks yang diperlukan tidak tersedia di file bapak
y_t = tf.transpose(y_2d)
y_t